variables:
  ECR_PROJECT: "workset"
  PROJECT_NAME: "clinvcf"

stages:
  - test
  - release
  - artefact_build
  - login
  - push-registry
  - security

.merge_request_rules: &merge_request_rules
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"

.release_rules: &release_rules
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"

include:
  - project: "seqone/services/template/push-ecr-registry"
    file:
      - "src/ecr-login.gitlab-ci.yml"
  - local: ".gitlab/ci/docker.gitlab-ci.yml"
  - local: ".gitlab/ci/login.gitlab-ci.yml"
  - local: ".gitlab/ci/retry.gitlab-ci.yml"
  - local: ".gitlab/ci/semantic-release.gitlab-ci.yml"
  - local: ".gitlab/ci/trivy.gitlab-ci.yml"

#################
# TEST
#################
test:
  image: registry.gitlab.com/seqone/internal/dockerfiles/nim-builder:1.6.14
  stage: test
  before_script:
    - apt-get update && apt-get install -y jq wget
  script:
    - apt-get update && apt-get install -y git
    - nimble build -y
    - nimble test
  tags:
    - bioinfo
  <<: *merge_request_rules

artefact_build:
  image: registry.gitlab.com/seqone/internal/dockerfiles/nim-builder:1.6.14
  stage: artefact_build
  script:
    - apt-get update && apt-get install -y git
    - nimble install -y
  artifacts:
    paths:
    - clinvcf
  tags:
    - bioinfo
  rules:
    - !reference [ .merge_request_rules, rules ]
    - !reference [ .release_rules, rules ]

push_registry_test:
  extends: .docker_push_registry_test
  variables:
    IMAGE_TAG: vtest
    DOCKERFILE_PATH: Dockerfile
  needs:
    - job: artefact_build
      artifacts: true
  <<: *merge_request_rules

security_test:
  extends: .trivy_scan
  variables:
    IMAGE_TAG: vtest
    DOCKERFILE_PATH: Dockerfile
  <<: *merge_request_rules

####################
# Release
####################
release:
  extends: .semantic_release
  stage: release
  <<: *release_rules

####################
# Delivery
####################
ecr_get_password_tag:
  stage: login
  extends: .ecr-get-password
  rules:
    - if: '$CI_COMMIT_TAG != null'

tag_push_registry:
  extends: .docker_push_registry_ecr
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG
    DOCKERFILE_PATH: Dockerfile
  rules:
    - if: '$CI_COMMIT_TAG != null'
  needs:
    - job: ecr_get_password_tag
      artifacts: true
    - job: artefact_build
      artifacts: true

ecr_get_password_latest:
  stage: login
  extends: .ecr-get-password
  <<: *release_rules

# Used in Dev only
latest_push_registry:
  extends: .docker_push_registry_ecr
  variables:
    IMAGE_TAG: "vlatest"
    DOCKERFILE_PATH: Dockerfile
  <<: *release_rules
  needs:
    - job: ecr_get_password_latest
      artifacts: true
    - job: artefact_build
      artifacts: true

