stages:
  - test
  - delivery

test:
  image: registry.gitlab.seq.one/devops/dockerfiles/nim-builder:1.0.2
  stage: test
  script:
    - nimble test
  tags:
    - docker-executor

delivery:
  image: registry.gitlab.seq.one/devops/dockerfiles/nim-builder:1.0.2
  stage: delivery
  script:
    - nimble install -y
  artifacts:
    paths:
    - clinvcf
  tags:
    - docker-executor
  only:
    - tags
